export default `
<div class="Main">
  <div class="Inner">
    <div class="Content">
      <div class="Eyebrow">27 AUGUST / REMOTE</div>
      <h1><strong>What not to do when remote working
</strong></h1>
      <h2>A simple guide on what to avoid when working at home.</h2>
    </div>
  </div>
  <div class="Watermark">
    Generated by <span class="Watermark-logo">OGIMPACT.SH</span>
  </div>
</div>
`;
